// Code generated by goctl. DO NOT EDIT.

package {{.pkg}}
{{.imports}}
{{.types}}
{{.new}}
{{.save}}
{{.batchSave}}
{{.deleteById}}
{{.deleteByIds}}
{{.findById}}
{{.findByIdWithField}}
{{.findByIdUnscoped}}
{{.findByIdUnscopedWithField}}
{{.findByIds}}
{{.findByIdsWithField}}
{{.findByIdsUnscoped}}
{{.findByIdsUnscopedWithField}}
{{.list}}
{{.listUnscoped}}
{{.listWithField}}
{{.listUnscopedWithField}}
{{.count}}
{{.countUnscoped}}
{{.page}}
{{.pageUnscoped}}
{{.pageWithField}}
{{.pageUnscopedWithField}}


